# Chapter 5 - Basic Math and Statistics
## Segment 1 - Using NumPy to perform arithmetic operations on data

In [2]:
import numpy as np
from numpy.random import randn

In [ ]:
np.set_printoptions(precision=2)

## Creating arrays
### Creating arrays using a list

In [3]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
b = np.array([[10,20,20],[40,50,60]])
b

array([[10, 20, 20],
       [40, 50, 60]])

### Creating arrays via assignment

In [6]:
np.random.seed(25)
c = 36*np.random.randn(6)
c

array([  8.21783123,  36.96805091, -30.22505456, -21.28253464,
       -34.44797868,  -8.003725  ])

In [7]:
d = np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

## Performing arthimetic on arrays

In [8]:
a*10

array([10, 20, 30, 40, 50, 60])

In [9]:
c+a

array([  9.21783123,  38.96805091, -27.22505456, -17.28253464,
       -29.44797868,  -2.003725  ])

In [10]:
c-a

array([  7.21783123,  34.96805091, -33.22505456, -25.28253464,
       -39.44797868, -14.003725  ])

In [11]:
c*a

array([   8.21783123,   73.93610183,  -90.67516369,  -85.13013858,
       -172.2398934 ,  -48.02234998])

In [12]:
c/a

array([  8.21783123,  18.48402546, -10.07501819,  -5.32063366,
        -6.88959574,  -1.33395417])

### Multiplying matrices and basic linear algebra